### ISSUE TITLE
Wolfe - Cheese microbiomes

### ISSUE THREAD

**Issue by micahvandegrift** [openknowledgecenter/fermentology#1]
transcript ready for light edit

**Comment by micahvandegrift** [comment]
Files in [GDrive](https://drive.google.com/drive/folders/1WQ8QmXWTNTRVkLJUQ-AetzxIfXfhDHbC)

**Comment by laurennichols** [comment]
Looks like this talk is also listed under the "project to-do". Is this a duplicate or a different talk?

**Comment by micahvandegrift** [comment]
> Looks like this talk is also listed under the "project to-do". Is this a duplicate or a different talk?

Duplicate - I deleted the other one. thanks!
