### ISSUE TITLE
[on hold] Enrich transcript: The Sourdough Club–A Conversation with Vanessa Kimbell

### ISSUE THREAD

**Issue by kvdufresne** [openknowledgecenter/fermentology#12]

**Comment by kvdufresne** [comment]
@micahvandegrift I am likely missing it - but where can we find this transcript? I can't seem to find it in our GDrive!

**Comment by micahvandegrift** [comment]
@kvdufresne ah yes! I don't think it'd run that one through the service yet. I think we need to check with Vanessa to see if she wants to be involved, since this talk was hosted through her IG live account. There'll be some licensing hurdles to jump through.
