### ISSUE TITLE
Zimmerman - viking mead

### ISSUE THREAD

**Issue by micahvandegrift** [openknowledgecenter/fermentology#2]
Update from Lauren: Author edited google doc text (https://docs.google.com/document/d/11fVELETV9216a3jeH2chSnQjn4dqzroOlP88YCNXMtw/edit?usp=sharing). Note Ive included some communication with the author about image usage at the bottom of the google doc.

**Comment by micahvandegrift** [comment]
Edited transcript [here](https://docs.google.com/document/d/1UilAbSBu3A5O4fqLCty1uD9dfKt7hNIMgNfQ1wf-Z3E/edit)

**Comment by laurennichols** [comment]
Author edited google doc text (https://docs.google.com/document/d/11fVELETV9216a3jeH2chSnQjn4dqzroOlP88YCNXMtw/edit?usp=sharing). Note Ive included some communication with the author about image usage at the bottom of the google doc.
